version: '3.7'
services:
  app-web:
    build: ./
    container_name: app-web
    ports:
      - "8080:8080"
    links:
      - app-db
    restart: unless-stopped

  app-db:
    image: postgres:latest
    container_name: app-db
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: Familiehjelpen
        PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/database/initDB.sql:/docker-entrypoint-initdb.d/initDB.sql
      - ./src/main/resources/database/populateDB.sql:/docker-entrypoint-initdb.d/populateDB.sql
    restart: unless-stopped

  app-db-data:
    image: cogniteev/echo
    container_name: app-init-db-data
    command: echo 'Data Container for PostgreSQL'
    depends_on:
      - app-db
    volumes:
      - /var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    links:
      - app-db
    ports:
      - "127.0.0.1:8181:80"
    restart: unless-stopped